version: '3.5'
services:
  api:
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/car/
    expose:
      - "8000"
    build:
      dockerfile: Dockerfile
      context: .
    command: /usr/bin/php -S localhost:8000
    restart: always